spring:
  ##数据源
  datasource:
    ##mysql
#    url : jdbc:mysql://localhost:3306/mitri?useUnicode=true&characterEncoding=UTF-8
#    username : root
#    password : root
#    driverClassName : com.mysql.jdbc.Driver
    url : jdbc:oracle:thin:@*********:1621:***
    username : *****
    password : *******
    driverClassName : oracle.jdbc.OracleDriver

mybatis:
  mapper-locations: classpath:mapper/*.xml